### ISSUE TITLE
Rename download package

### ISSUE THREAD

**Issue by nunoleite** [akeeba/panopticon-connector-wordpress#1]
Hi!

Could you rename the download package to something like "wordpress-panopticon-1.0.1.zip" so it doesn't have the same name as the Akeeba Panopticon?

Thanks

**Comment by nikosdion** [comment]
No. They are different repositories, different versions, and _very_ different sizes.

**Comment by nunoleite** [comment]
Hi!
I understand, but downloading the files to install, may be confusing.
If i download the panopticon to a folder and then download the wordpress connector, they will have the same name, changing only the version. If i download the other connectors to install on the websites the name doesn't represent the platform for what they are.
After some versions they will be mixed, or the user have to rename it to know what it is, or it will think that they are the same.
![image](https://github.com/user-attachments/assets/f4797dda-f304-4b14-afdc-714952f33979)
If i didn't rename the files to know what they are, after some time i will never would know what they represent.
I even renamed some files as J3 and J4, so i know what they are, because i will have to install the correct version in each cms.
Thanks

**Comment by nikosdion** [comment]
The connector package names follow the naming conventions of the CMS they are built for.

You are free to use whichever organisation system works best for you. You want to rename the files? That's cool. You want to use subdirectories? That's cool too.

What is NOT cool, acceptable, or even reasonable is asking me to spend hours to address installation, update, and release issues stemming from renaming the package names of four different pieces of software because you're too lazy to spend 10 seconds to create four subdirectories to organise your downloads.

**Comment by nunoleite** [comment]
> The connector package names follow the naming conventions of the CMS they are built for.
> 
> You are free to use whichever organisation system works best for you. You want to rename the files? That's cool. You want to use subdirectories? That's cool too.
> 
> What is NOT cool, acceptable, or even reasonable is asking me to spend hours to address installation, update, and release issues stemming from renaming the package names of four different pieces of software because you're too lazy to spend 10 seconds to create four subdirectories to organise your downloads.

Understood.
You didn't have to be so rude. I was just trying to help, but now i understand why is done like that.

**Comment by nikosdion** [comment]
I tried being far more subtle before, but the point wasn't getting across.

Also, no, your request doesn't help anyone with anything. It was completely self-serving and entitled. You considered your ten seconds to create four subdirectories to be far more valuable than my time making changes to the software.

So, please, keep your indignation to yourself.

Over and out.
