### ISSUE TITLE
error "You did not specify a secret key." when adding a Wordpress site

### ISSUE THREAD

**Issue by CankarjevDomDeveloper** [akeeba/panopticon-connector-wordpress#2]
Greetings;
when I try to add an Wordpress site I seem to get a working connector on the site; 
![panopticon_Wordpress](https://github.com/user-attachments/assets/5d654dd6-efb9-4a6a-92ef-c866d3e05ad4)
but then i try to add the page get this error:
![panopticon_Wordpress2](https://github.com/user-attachments/assets/9f9649ef-f84b-4bb5-a378-4d0a31271575)

I have a 2FA auth enabled via miniOrange 2-FA plugin. Is it possible this is the reason for error?

Thank you for your assistance & best regards,

**Comment by nikosdion** [comment]
Please read https://github.com/akeeba/panopticon/discussions/782
